# Generated by Django 3.2.6 on 2021-08-10 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_app', '0004_auto_20210802_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='key_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.product', verbose_name='Название заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='key_product_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказал пользователь'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название категории')),
                ('product_foregin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.product', verbose_name='Название продукта')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категория',
            },
        ),
    ]
