# Generated by Django 3.2.6 on 2021-08-10 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_auto_20210810_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='product_foregin',
        ),
        migrations.AddField(
            model_name='product',
            name='categories_foregin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm_app.categories', verbose_name='Название продукта'),
            preserve_default=False,
        ),
    ]
