# Generated by Django 3.2.6 on 2021-08-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_auto_20210811_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=2, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
